---
- name: configure SNMP
  hosts: cisco
  gather_facts: false

  tasks:

    - name: use snmp resource module
      cisco.ios.snmp_server:
        state: merged          
        config:            
          location: 'Dublin'
          packet_size: 700
          communities:
            - acl_v4: acl_uq
              name: Durham-community
              rw: true
            - acl_v4: acl_uq
              name: ChapelHill-community
              rw: true  
